host: "http://smartdevice.ai.tuling123.com/speech/chat"
turing:
  url: "http://smartdevice.ai.tuling123.com/speech/chat"
  apiKey: "b8bfa00d66264e41afc0c91b1850f855"
  secret: "09h928747iO6bJ7S"
  uid: "ac96068d8631ad2323dabd31040ca599"
  deviceId: "ai11223344556677"

logger:
  name: "turing"
  logger_level: 'DEBUG'
  stream_handler_level: 'DEBUG'
  file: 'chameleon'
  file_handler_level: 'DEBUG'
  fmt_str: 'Time:%(asctime)s---日志等级：%(levelname)s---收集器名称:%(name)s---日志:%(message)s---%(filename)s---%(lineno)s---'
